In [1]:
import torch
import torch.nn as nn

In [3]:
class Model(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out
    

features = torch.rand(10,5)

model = Model(num_features=features.shape[1])

ypred = model(features)

In [5]:
model.linear.weight, model.linear.bias

(Parameter containing:
 tensor([[-0.4212, -0.2535,  0.3499, -0.1368,  0.0509]], requires_grad=True),
 Parameter containing:
 tensor([0.3750], requires_grad=True))

In [6]:
!pip install torchinfo

In [7]:
from torchinfo import summary

summary(model, input_size=(features.shape))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [10]:
# more complex

class Model(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        self.linear1 = nn.Linear(num_features, 3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3, 1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, features):
        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        return out

In [11]:
model = Model(num_features=features.shape[1])

model(features)

tensor([[0.4252],
        [0.4278],
        [0.4210],
        [0.4257],
        [0.4247],
        [0.4217],
        [0.4278],
        [0.4278],
        [0.4226],
        [0.4260]], grad_fn=<SigmoidBackward0>)

In [12]:
model.linear1.weight, model.linear1.bias

(Parameter containing:
 tensor([[-0.0828,  0.1246, -0.1364,  0.4072, -0.1741],
         [-0.3466, -0.3257,  0.2658, -0.2149, -0.2168],
         [-0.3205,  0.2554, -0.3551,  0.0694,  0.4021]], requires_grad=True),
 Parameter containing:
 tensor([-0.4138,  0.4031, -0.0787], requires_grad=True))

In [13]:
model.linear2.weight, model.linear2.bias

(Parameter containing:
 tensor([[-0.2970, -0.0670, -0.0241]], requires_grad=True),
 Parameter containing:
 tensor([-0.2907], requires_grad=True))

In [14]:
summary(model, input_size=(features.shape))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [15]:
features.shape

torch.Size([10, 5])

In [16]:
# improving it

class Model(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3, 1),
            nn.Sigmoid()
        )
    
    def forward(self, features):
        out = self.network(features)
        return out

In [17]:
model = Model(num_features=5)

model(features)

tensor([[0.5655],
        [0.5988],
        [0.5743],
        [0.5634],
        [0.5368],
        [0.5692],
        [0.5923],
        [0.6016],
        [0.5588],
        [0.5790]], grad_fn=<SigmoidBackward0>)