In [1]:
import torch

In [2]:
torch.__version__

'2.9.0+cu126'

In [4]:
if torch.cuda.is_available():
    print('GPU is available!')
    print(torch.cuda.get_device_name(0))
else:
    print('GPU not aval, using CPU')

GPU is available!
Tesla T4


In [6]:
# using empty

a = torch.empty(2,3)

print(a)

print(type(a))

tensor([[3.1119e-02, 4.3196e-41, 6.4801e-02],
        [0.0000e+00, 4.4842e-44, 0.0000e+00]])
<class 'torch.Tensor'>


In [7]:
# using zeros

torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
# using ones

torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
# using rand

torch.rand(2,3)

tensor([[1.0442e-01, 2.3230e-01, 3.0740e-01],
        [6.7417e-01, 8.9611e-01, 2.2179e-04]])

In [11]:
# seed

torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [13]:
# using tensor

torch.tensor([[1,2,3], [3,5,6]])

tensor([[1, 2, 3],
        [3, 5, 6]])

In [21]:
# torch arange

print(torch.arange(0,20,2))
print(torch.linspace(1,10,10))
print(torch.eye(5))
print(torch.full((2,2), 4))

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([[4, 4],
        [4, 4]])


In [22]:
# shape

x = torch.tensor([[1,2,3],[1,3,4]])

x.shape

torch.Size([2, 3])

In [23]:
# empty like

torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [24]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [25]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [26]:
# find data type

x.dtype

torch.int64

In [27]:
# assign data type

torch.tensor([[1.0, 2.0, 3.0]], dtype=torch.int32)

tensor([[1, 2, 3]], dtype=torch.int32)

In [28]:
# using to()

x.to(torch.float16)

tensor([[1., 2., 3.],
        [1., 3., 4.]], dtype=torch.float16)

In [32]:
# rand_like, you need to specity the data type to torch.float32 only

torch.manual_seed(20)
torch.rand_like(x, dtype=torch.float16)

tensor([[0.6733, 0.2314, 0.1323],
        [0.6089, 0.4512, 0.6064]], dtype=torch.float16)

In [34]:
# addition

x + 2

tensor([[3, 4, 5],
        [3, 5, 6]])

In [35]:
# substract

x - 2

tensor([[-1,  0,  1],
        [-1,  1,  2]])

In [36]:
# multi

x*2

tensor([[2, 4, 6],
        [2, 6, 8]])

In [37]:
# division

x/3

tensor([[0.3333, 0.6667, 1.0000],
        [0.3333, 1.0000, 1.3333]])

In [38]:
# int division

x//3

tensor([[0, 0, 1],
        [0, 1, 1]])

In [39]:
# mod

x%2

tensor([[1, 0, 1],
        [1, 1, 0]])

In [42]:
y = torch.rand_like(x, dtype=torch.float16)

In [44]:
x + y, x*y, x/y, x**y, x//y, x%y

(tensor([[1.1914, 2.6973, 3.9121],
         [1.8857, 3.7852, 4.5781]], dtype=torch.float16),
 tensor([[0.1919, 1.3945, 2.7344],
         [0.8857, 2.3535, 2.3164]], dtype=torch.float16),
 tensor([[5.2109, 2.8691, 3.2910],
         [1.1289, 3.8242, 6.9062]], dtype=torch.float16),
 tensor([[1.0000, 1.6211, 2.7227],
         [1.0000, 2.3672, 2.2324]], dtype=torch.float16),
 tensor([[5., 2., 3.],
         [1., 3., 6.]], dtype=torch.float16),
 tensor([[0.0405, 0.6055, 0.2651],
         [0.1143, 0.6460, 0.5254]], dtype=torch.float16))

In [47]:
a = torch.tensor([1,-2,3])

print(torch.neg(a))
print(torch.abs(a))

tensor([-1,  2, -3])
tensor([1, 2, 3])


In [50]:
torch.round(y)

tensor([[0., 1., 1.],
        [1., 1., 1.]], dtype=torch.float16)

In [52]:
torch.ceil(y)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float16)

In [53]:
torch.floor(y)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)

In [ ]:
# num less than 2 will become 2 and num more than 3 will become 3

torch.clamp(x, min=2, max=3)

tensor([[2, 2, 3],
        [2, 3, 3]])

In [56]:
torch.sum(x)

tensor(14)

In [57]:
torch.sum(x, dim=0)

tensor([2, 5, 7])

In [58]:
torch.sum(x, dim=1)

tensor([6, 8])

In [63]:
# work with float only
torch.mean(x.to(torch.float16), dim=1)

tensor([2.0000, 2.6660], dtype=torch.float16)

In [ ]:
torch.argmax(x) # also work with dim = 0,1

tensor([0, 1, 1])

In [68]:
f = torch.rand(3,2)
g = torch.rand(2,3)

In [69]:
torch.matmul(f,g)

tensor([[0.3092, 0.1497, 0.4572],
        [0.5616, 0.3000, 0.7376],
        [0.6032, 0.3092, 0.8355]])

In [75]:
torch.dot(x.flatten(), y.to(torch.int64).flatten())

tensor(0)

In [80]:
x.T

tensor([[1, 1],
        [2, 3],
        [3, 4]])

In [82]:
torch.transpose(x, 1, 0)

tensor([[1, 1],
        [2, 3],
        [3, 4]])

In [ ]:
x > y

tensor([[True, True, True],
        [True, True, True]])

In [91]:
torch.softmax(y, dim=0)

tensor([[0.3333, 0.4783, 0.5825],
        [0.6670, 0.5220, 0.4177]], dtype=torch.float16)

In [94]:
torch.selu(y)

tensor([[0.2017, 0.7324, 0.9580],
        [0.9307, 0.8242, 0.6084]], dtype=torch.float16)

In [95]:
# instead of creating new tensor which occupy additional space, we can do inplace changes

m = torch.rand(3,3)
n = torch.rand(3,3)

m.add_(n)

tensor([[1.0312, 0.6248, 1.5837],
        [0.4944, 1.0291, 1.1173],
        [0.2472, 1.2461, 0.5706]])

In [ ]:
m.relu_() #inplace changes

tensor([[1.0312, 0.6248, 1.5837],
        [0.4944, 1.0291, 1.1173],
        [0.2472, 1.2461, 0.5706]])

In [99]:
m

tensor([[1.0312, 0.6248, 1.5837],
        [0.4944, 1.0291, 1.1173],
        [0.2472, 1.2461, 0.5706]])

In [100]:
# copying tensor

p = torch.rand(2,2)

In [101]:
q = p

In [102]:
q

tensor([[0.1845, 0.0817],
        [0.0495, 0.5198]])

In [104]:
p.mul_(2)

tensor([[0.3690, 0.1633],
        [0.0991, 1.0395]])

In [105]:
q

tensor([[0.3690, 0.1633],
        [0.0991, 1.0395]])

In [109]:
id(p) == id(q)

True

In [110]:
r = p.clone()

In [114]:
p.subtract_(10)

tensor([[-9.6310, -9.8367],
        [-9.9009, -8.9605]])

In [116]:
p, r

(tensor([[-9.6310, -9.8367],
         [-9.9009, -8.9605]]),
 tensor([[0.3690, 0.1633],
         [0.0991, 1.0395]]))

In [117]:
id(p) == id(r)

False

In [118]:
torch.cuda.is_available()

True

In [119]:
device = torch.device('cuda')

In [ ]:
torch.rand((2,3), device=device) # created on GPU

tensor([[0.7680, 0.9209, 0.5808],
        [0.9348, 0.4126, 0.8324]], device='cuda:0')

In [ ]:
# moving existing tensor to GPU

a.to(device)

tensor([ 1, -2,  3], device='cuda:0')

In [126]:
i = torch.rand(2,3,4)

In [130]:
i.permute(2,1,0) # means 2nd index wala shape will come first (4), then 3 at 2nd place and 0 wala at last

tensor([[[0.6008, 0.8116],
         [0.0261, 0.4900],
         [0.9292, 0.2768]],

        [[0.7614, 0.8201],
         [0.9486, 0.2658],
         [0.4402, 0.7972]],

        [[0.9115, 0.2351],
         [0.4727, 0.1319],
         [0.6012, 0.7241]],

        [[0.7944, 0.7374],
         [0.7817, 0.9753],
         [0.8573, 0.1374]]])

In [137]:
# unsqueeze -> add new dim

x.unsqueeze(0)

tensor([[[1, 2, 3],
         [1, 3, 4]]])

In [138]:
import numpy as np

In [140]:
# pytorch tensor to np

a = torch.rand(2,3)

a.numpy()

array([[0.70715195, 0.5547898 , 0.5563673 ],
       [0.55466545, 0.07986474, 0.07400674]], dtype=float32)

In [143]:
# numpy to pytorch tensor

a = np.array([1,3,3])

torch.from_numpy(a)

tensor([1, 3, 3])